# Generated by Django 4.1.7 on 2024-08-06 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeTable', '0002_classroom_timetable_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='division',
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='timeTable.course'),
            preserve_default=False,
        ),
    ]
