# Generated by Django 4.1.7 on 2024-08-06 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeTable', '0003_remove_subject_division_subject_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='timeTable.semester'),
            preserve_default=False,
        ),
    ]
