# Generated by Django 4.1.7 on 2024-08-11 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeTable', '0007_faculty_timetable_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timeTable.faculty'),
        ),
    ]
