# Generated by Django 4.1.7 on 2024-08-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeTable', '0008_timetable_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='classroom',
        ),
    ]
