# Generated by Django 4.1.7 on 2024-08-11 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeTable', '0009_remove_timetable_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timeTable.classroom'),
            preserve_default=False,
        ),
    ]
