# Generated by Django 4.1.7 on 2024-08-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTable', '0011_timetable_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='start_time',
        ),
        migrations.AddField(
            model_name='timetable',
            name='time',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
