# Generated by Django 4.1.7 on 2024-08-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTable', '0012_remove_timetable_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='time',
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_slot',
            field=models.CharField(choices=[('07:00-08:30', '07:00 - 08:30'), ('08:30-09:45', '08:30 - 09:45'), ('09:45-10:30', '09:45 - 10:30'), ('10:30-11:30', '10:30 - 11:30'), ('11:30-13:00', '11:30 - 13:00')], max_length=20, null=True),
        ),
    ]
