# Generated by Django 4.1.7 on 2024-08-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTable', '0013_remove_timetable_time_timetable_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='division',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time_slot',
            field=models.CharField(choices=[('07:00-08:00', '07:00 - 08:00'), ('08:00-09:00', '08:00 - 09:00'), ('09:00-10:30', '09:00 - 10:00'), ('10:30-11:30', '10:30 - 11:30'), ('11:30-12:30', '11:30 - 12:30')], max_length=20, null=True),
        ),
    ]
